name: Publish NPM Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    # - name: Install dependencies
    #   run: npm install

    - name: Configure npm authentication
      run: echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Set up this secret in your repository settings

    - name: Determine Version Bump
      id: determine_bump
      run: |
        MESSAGE=$(git log -1 --pretty=%B)
        if echo "$MESSAGE" | grep -qi "BREAKING CHANGE"; then
          echo "major"
        elif echo "$MESSAGE" | grep -qi "feat:"; then
          echo "minor"
        else
          echo "patch"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Bump Version
      run: npm version ${{ steps.determine_bump.outputs.major_minor_patch }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Push Changes
      run: git push --follow-tags
